apiVersion: v1
kind: Service
metadata:
  name: moodfood-backend
  namespace: moodfood-ai
spec:
  selector:
    app: moodfood-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
