apiVersion: v1
kind: Service
metadata:
  name: moodfood-frontend
  namespace: moodfood-ai
spec:
  selector:
    app: moodfood-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
