apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: moodfood-ai
type: Opaque
stringData:
  jwt-secret: supersecretvalue

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: moodfood-ai
type: Opaque
stringData:
  postgres-password: postgres
